#!/usr/bin/env python3

"""Not documented.
"""

import datetime
from lxml import etree as ET
import sys
import argparse
import json

from ixbrl_parse.ixbrl import parse

maxwidth=40

parser = argparse.ArgumentParser(
    description=__doc__
)
parser.add_argument('inputs', metavar='inputs', nargs=2,
                    help='Input files to compare')

# Parse arguments
args = parser.parse_args(sys.argv[1:])

tree1 = ET.parse(args.inputs[0])
tree2 = ET.parse(args.inputs[1])

i1 = parse(tree1)
i2 = parse(tree2)

rels1 = i1.to_dict()
rels2 = i2.to_dict()

indexes = {}

def compare(a, b, index=""):

    for key, value in a.items():

        if isinstance(value, dict):
            if key in b:
                compare(value, b[key], index + "." + key)
        else:
            if key in b:
                vala = str(a[key])[:40]
                valb = str(b[key])[:40]
                if vala != valb:
                    print("Anomaly at", index + "." + key)
                    print("  A:", vala)
                    print("  B:", valb)
                    print()

compare(rels1, rels2)

