#!/usr/bin/env python3

"""Reads an iXBRL file on input, and outputs a JSON representation.
"""

import datetime
from lxml import etree as ET
import sys
import argparse
import json

from ixbrl_parse.ixbrl import parse

maxwidth=40

parser = argparse.ArgumentParser(
    description=__doc__
)
parser.add_argument('--input', '-i',
                    required=True,
                    help='Input computations file')
parser.add_argument('--format', '-f',
                    default="n3",
                    help='Output format (default: n3)')
parser.add_argument('--verbose', '-v', action='store_true',
                    help='Turn on verbose output.')

# Parse arguments
args = parser.parse_args(sys.argv[1:])

tree = ET.parse(args.input)

i = parse(tree)
if args.verbose:
    sys.stderr.write("Read %s.\n" % args.input)

rels = i.to_dict()

print(json.dumps(rels, indent=4))

